package org.snowflake;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import org.snowflake.devserver.StaticContentController;
import org.snowflake.devserver.StaticContentView;
import org.snowflake.fieldconverters.FieldConverter;
import org.snowflake.utils.Console;
import org.snowflake.utils.UrlHelpers;
import org.snowflake.views.View;
import org.snowflake.views.ViewFactory;
import org.snowflake.views.scaffolding.FormFieldTemplateGenerator;
import org.snowflake.views.velocity.VelocityViewFactory;
import org.snowflake.views.velocity.scaffolding.FormScaffoldGenerator;

/**
 * A WebApp has a number of pages which in turn have methods, bound to URLs.
 * Page objects can be of any type, and are registered with
 * {@link WebApp#registerController(String, Object)}.
 * <p />
 * Ideas:
 * <ul>
 * <li />Introduce a notion of Feature Set, as in MMF?
 * </ul>
 * Backlog:
 * <ul>
 * <li />TODO: Pluggable mechanism for determining what field is an ID (must be
 * based on type introspection and variable name)
 * </ul>
 * 
 * @author haugeto
 */
public class WebApp {

    public static final String SNOWFLAKE_CSS = "/static/org/snowflake/snowflake.css";

    protected final Map<Object, WebPage> webPages = new LinkedHashMap<Object, WebPage>();

    protected final Set<FormFieldTemplateGenerator> formFieldTemplateGenerators = new LinkedHashSet<FormFieldTemplateGenerator>();

    protected final Set<FieldConverter> fieldConverters = new LinkedHashSet<FieldConverter>();

    protected final Set<RequestInterceptor<?>> requestInterceptors = new LinkedHashSet<RequestInterceptor<?>>();

    protected ViewFactory viewFactory = new VelocityViewFactory(this);

    protected final String name;

    protected final String appBaseUrl;

    protected final String defaultViewCss;

    protected String defaultFooter = "Powered by Snowflake MVC";

    public WebApp() {
        this("Snowflake");
    }

    public WebApp(String name) {
        this(name, "", Arrays.asList(FormScaffoldGenerator.DEFAULT_GENERATORS));
    }

    public WebApp(String name, String baseUrl) {
        this(name, baseUrl, Arrays.asList(FormScaffoldGenerator.DEFAULT_GENERATORS));
    }

    public WebApp(String name, String baseUrl, Collection<FormFieldTemplateGenerator> formFieldTemplateGenerators) {
        this.name = name;
        this.appBaseUrl = UrlHelpers.normalize(baseUrl);
        this.defaultViewCss = baseUrl + SNOWFLAKE_CSS;
        this.fieldConverters.addAll(Arrays.asList(FieldConverter.DEFAULT_CONVERTERS));
        this.formFieldTemplateGenerators.addAll(formFieldTemplateGenerators);
    }

    /**
     * Register a page as a part of the web application run by this Server.
     * 
     * @param urlPrefix
     *            Suffix for URLs to be handled by the given controller page
     * @param controller
     *            The client object to handle incoming HTTP requests. NB:
     *            Overloaded methods not supported yet.
     */
    public WebPage registerController(String urlPrefix, Object controller) {
        urlPrefix = UrlHelpers.normalize(urlPrefix);
        if (controller == null) {
            throw new IllegalArgumentException("controller cannot be null");
        }
        if (urlPrefix.startsWith("/static")) {
            throw new IllegalArgumentException("URL prefix \"/static\" is reserved for static content");
        }
        WebPage webPage = new WebPage(controller, this.appBaseUrl + urlPrefix);
        registerController(webPage);
        return webPage;
    }

    public void registerController(WebPage webPage) {
        Set<Class<?>> argumentTypesToIgnore = new HashSet<Class<?>>();
        for (RequestInterceptor<?> requestInterceptor : this.requestInterceptors) {
            Class<?> type = requestInterceptor.getType();
            if (type != null)
                argumentTypesToIgnore.add(type);
        }
        webPage.createWebMethods(argumentTypesToIgnore);
        this.webPages.put(webPage.getController(), webPage);
    }

    public Answer createAnswer(WebMethod webMethod) {
        Answer answer = new Answer();
        answer.setTitle((getName() + ((webMethod.isDefaultMethod()) ? "" : " - " + webMethod.getName())));
        answer.setFooter(defaultFooter);
        answer.setCss(defaultViewCss);
        answer.setTemplateFile(webMethod.getTemplateFileName());
        answer.setAutoGenerated(!webMethod.hasViewTemplateFile());
        if (webMethod.getNext() != null) {
            answer.setNextUrl(webMethod.getNext().getUrl());
        }
        return answer;
    }

    public void setViewFactory(ViewFactory viewFactory) {
        this.viewFactory = viewFactory;
    }

    public void setLayoutTemplate(String classPathResource) {
        this.viewFactory.setLayoutTemplate(classPathResource);
    }

    public WebPage getWebPageForControllerClass(Class<?> controllerClass) {
        for (WebPage webPage : webPages.values()) {
            if (webPage.getController().getClass() == controllerClass) {
                return webPage;
            }
        }
        throw new IllegalArgumentException("Unregistered controller class: " + controllerClass);
    }

    public WebPage getWebPageForController(Object controller) {
        for (WebPage webPage : webPages.values()) {
            if (webPage.getController().equals(controller)) {
                return webPage;
            }
        }
        throw new IllegalArgumentException("Unregistered controller: " + controller);
    }

    public WebPage getWebPageByName(String name) {
        return this.webPages.get(name);
    }

    public Set<WebPage> getWebPages() {
        return new LinkedHashSet<WebPage>(this.webPages.values());
    }

    public void add(FormFieldTemplateGenerator generator) {
        formFieldTemplateGenerators.add(generator);
    }

    public Set<FormFieldTemplateGenerator> getFormFieldTemplateGenerators() {
        return new LinkedHashSet<FormFieldTemplateGenerator>(this.formFieldTemplateGenerators);
    }

    public void addFieldConverter(FieldConverter fieldConverter) {
        this.fieldConverters.add(fieldConverter);
    }

    protected FieldConverter findConverterForType(Class<?> type) {
        for (FieldConverter fieldConverter : this.fieldConverters) {
            if (fieldConverter.accepts(type))
                return fieldConverter;
        }
        return null;
    }

    public WebRequest createWebRequest(WebPage webPage, WebMethod webMethod, Question question, Answer answer) {
        return new WebRequest(this, webPage, webMethod, question, answer);
    }

    public String getName() {
        return this.name;
    }

    /**
     * Add a RequestInterceptor that will be given the chance to pre- and post
     * process a request to the application.
     */
    public void addRequestInterceptor(RequestInterceptor<?> requestInterceptor) {
        if (!this.webPages.isEmpty()) {
            throw new IllegalStateException("addRequestInterceptor must be invoked before registerController");
        }
        this.requestInterceptors.add(requestInterceptor);
    }

    /**
     * Get a copy of the request interceptors currently registered.
     */
    public List<RequestInterceptor<?>> getRequestInterceptors() {
        return new ArrayList<RequestInterceptor<?>>(this.requestInterceptors);
    }

    public String getDefaultViewCss() {
        return defaultViewCss;
    }

    public WebPage pageForWebMethod(WebMethod webMethod) {
        for (WebPage webPage : this.webPages.values()) {
            if (webPage.getWebMethods().contains(webMethod)) {
                return webPage;
            }
        }
        return null;
    }

    public Class<?> deduceCollectionType(WebMethod indexMethod) {
        WebPage page = pageForWebMethod(indexMethod);
        for (WebMethod webMethod : page.getWebMethods()) {
            if (webMethod.getType() == WebMethodType.SUBMIT) {
                return webMethod.getHttpArgType();
            }
        }
        return null;
    }

    public WebMethod indexMethodForType(Class<?> fieldType) {
        for (WebPage webPage : getWebPages()) {
            Set<WebMethod> webMethods = webPage.getWebMethods();
            for (WebMethod webMethod : webMethods) {
                if (webMethod.getHttpArgType() == fieldType) {
                    if (webMethod.getType() == WebMethodType.SUBMIT) {
                        return webPage.getWebMethodByName("index");
                    }
                }
            }
        }
        return null;
    }

    public Set<WebPage> initializeContexts() {
        Set<WebPage> result = new LinkedHashSet<WebPage>();
        result.addAll(initializeDynamicContentContexts());
        result.addAll(initializeStaticContentContexts());
        return result;
    }

    public Set<WebPage> initializeDynamicContentContexts() {
        Console.center(name);
        LinkedHashSet<WebPage> result = new LinkedHashSet<WebPage>();
        for (WebPage webPage : webPages.values()) {
            for (WebMethod webMethod : webPage.getWebMethods()) {
               
                String description = webPage.getController().getClass().getSimpleName() + "." + webMethod.getName();

                if (webMethod.getNext() != null) {
                    description += " (submits to " + webMethod.getNext().getName() + ")";
                }
                if (webMethod.reusesView()) {
                    description += " (reuses view of " + webMethod.getReuseViewMethod().getName() + ")";
                }
                description += " " + webMethod.getHttpMethod();

                Console.justify(webMethod.getUrl(), description, '.');
                View view = viewFactory.createView(webMethod);
                webMethod.setView(view);
            }
            result.add(webPage);
        }
        return result;
    }

    public Set<WebPage> initializeStaticContentContexts() {
        LinkedHashSet<WebPage> result = new LinkedHashSet<WebPage>();
        WebPage staticWebPage = new WebPage(new StaticContentController(), appBaseUrl + "/static");
        staticWebPage.createWebMethods(new HashSet<Class<?>>());
        webPages.put(staticWebPage.getBaseUrl(), staticWebPage);
        for (WebMethod staticContentMethod : staticWebPage.getWebMethods()) {
            staticContentMethod.setView(new StaticContentView());
        }
        result.add(staticWebPage);
        return result;
    }

    public void initViewEngine() {
        viewFactory.initialize();
    }

    public WebMethod resolveTargetMethod(String requestUrl) {
        String url = UrlHelpers.normalize(requestUrl);
        TreeMap<String, WebMethod> allWebMethods = allWebMethods();
        for (String key : allWebMethods.descendingKeySet()) {
            if (url.startsWith(key))
                return allWebMethods.get(key);
        }
        return null;
    }

    public TreeMap<String, WebMethod> allWebMethods() {
        Set<WebPage> webPages = getWebPages();
        TreeMap<String, WebMethod> allWebMethods = new TreeMap<String, WebMethod>();
        for (WebPage webPage : webPages) {
            for (WebMethod webMethod : webPage.getWebMethods())
                allWebMethods.put(webMethod.getUrl(), webMethod);
        }
        return allWebMethods;
    }

}